window.AGNEXUS_PRODUCTS = [
  {
    "id": "ali-proj-001",
    "source": "aliexpress",
    "category": "Proyectores ANSI",
    "title": "Proyector Touyinger Z7 Linux HDR10+ 1080P 4K 1200 ANSI",
    "processor": "AliExpress",
    "processorFamily": "Proyectores ANSI",
    "ram": "-",
    "storage": "-",
    "display": "-",
    "secondary": "AliExpress · 1200 ANSI lumenes · Linux/HDR10+ · 1080P nativo",
    "description": "Proyector con alto brillo ANSI para cine en casa y presentaciones con buena luz ambiental.",
    "price": 260,
    "originUrl": "https://es.aliexpress.com/item/1005012344223283.html",
    "sourcePrice": 149.57,
    "priceRule": "+110 y redondeo a decena superior",
    "lumenAnsi": 1200,
    "rawTitle": "Proyector Touyinger Z7 con Sistema Linux, HDR10+, Full HD 1080P, Compatible con 4K, 1200 ANSI Lumenes, Enfoque Automatico, Portatil, para Interiores y Exteriores, Proyector Inteligente",
    "image": "assets/products/ali-proj-001-proyector-touyinger-z7-linux-hdr10-1080p-4k-1200-ansi.jpg"
  },
  {
    "id": "ali-proj-002",
    "source": "aliexpress",
    "category": "Proyectores ANSI",
    "title": "Proyector Touyinger Z7 1080P 4K 1200 ANSI Smart TV",
    "processor": "AliExpress",
    "processorFamily": "Proyectores ANSI",
    "ram": "-",
    "storage": "-",
    "display": "-",
    "secondary": "AliExpress · 1200 ANSI lumenes · Smart TV · Soporte 360",
    "description": "Modelo compacto de alto brillo ANSI con enfoque en cine en casa y uso flexible.",
    "price": 250,
    "originUrl": "https://es.aliexpress.com/item/1005011624160042.html",
    "sourcePrice": 137.13,
    "priceRule": "+110 y redondeo a decena superior",
    "lumenAnsi": 1200,
    "rawTitle": "Proyector Touyinger Z7 1080P HD 4K Smart TV 1200 ANSI Lumenes, Proyector de Video para Cine en Casa con Soporte de 360 Mini Beam",
    "image": "assets/products/ali-proj-002-proyector-touyinger-z7-1080p-4k-1200-ansi-smart-tv.jpg"
  },
  {
    "id": "ali-proj-003",
    "source": "aliexpress",
    "category": "Proyectores ANSI",
    "title": "Proyector Touyinger L9W Ultra 4K 1080P 1000 ANSI",
    "processor": "AliExpress",
    "processorFamily": "Proyectores ANSI",
    "ram": "-",
    "storage": "-",
    "display": "-",
    "secondary": "AliExpress · 1000 ANSI lumenes · Enfoque automatico · Wifi6/BT",
    "description": "Proyector de 1000 ANSI con conectividad moderna para entretenimiento y productividad.",
    "price": 230,
    "originUrl": "https://es.aliexpress.com/item/1005012325397628.html",
    "sourcePrice": 115.11,
    "priceRule": "+110 y redondeo a decena superior",
    "lumenAnsi": 1000,
    "rawTitle": "Proyector Touyinger L9W Ultra, Compatible con 4K 1080P, 2G+32G, 1000 ANSI, Enfoque Automatico y Correccion Trapezoidal, Wifi6, BT, Cine en Casa",
    "image": "assets/products/ali-proj-003-proyector-touyinger-l9w-ultra-4k-1080p-1000-ansi.jpg"
  },
  {
    "id": "ali-gls-001",
    "source": "aliexpress",
    "category": "Gafas IA",
    "title": "Gafas Lenovo IA 8K HD con traduccion en tiempo real",
    "processor": "AliExpress",
    "processorFamily": "Gafas IA",
    "ram": "-",
    "storage": "-",
    "display": "-",
    "secondary": "AliExpress · Traduccion en tiempo real · Bluetooth · Camara integrada",
    "description": "Gafas inteligentes orientadas a traduccion de idiomas, llamadas y grabacion ligera.",
    "price": 110,
    "originUrl": "https://es.aliexpress.com/item/1005012432973677.html",
    "sourcePrice": 38.53,
    "priceRule": "+70 y redondeo a decena superior",
    "lumenAnsi": null,
    "rawTitle": "Gafas Inteligentes Lenovo 8K HD con IA, Camara de 1600W, Traduccion en Tiempo Real, Llamadas Bluetooth, Grabacion de Audio y Video, Reproduccion de Musica, Gafas de Sol 2026",
    "image": "assets/products/ali-gls-001-gafas-lenovo-ia-8k-hd-con-traduccion-en-tiempo-real.jpg"
  },
  {
    "id": "ali-gls-002",
    "source": "aliexpress",
    "category": "Gafas IA",
    "title": "Gafas Xiaomi IA 8K HD con traduccion y dialogo",
    "processor": "AliExpress",
    "processorFamily": "Gafas IA",
    "ram": "-",
    "storage": "-",
    "display": "-",
    "secondary": "AliExpress · Traduccion y dialogo IA · Camara 8K HD · Luz LED",
    "description": "Gafas de traduccion IA pensadas para viajes y uso diario con funciones multimedia.",
    "price": 110,
    "originUrl": "https://es.aliexpress.com/item/1005012242662688.html",
    "sourcePrice": 32.09,
    "priceRule": "+70 y redondeo a decena superior",
    "lumenAnsi": null,
    "rawTitle": "Gafas Inteligentes Xiaomi con IA, Camara 8K HD, Luz LED, Traduccion, Dialogo, Grabacion de Video, Gafas de Sol Deportivas para Exteriores, Novedad 2026",
    "image": "assets/products/ali-gls-002-gafas-xiaomi-ia-8k-hd-con-traduccion-y-dialogo.jpg"
  },
  {
    "id": "ali-gls-003",
    "source": "aliexpress",
    "category": "Gafas IA",
    "title": "Gafas IA con traduccion, bluetooth y control tactil",
    "processor": "AliExpress",
    "processorFamily": "Gafas IA",
    "ram": "-",
    "storage": "-",
    "display": "-",
    "secondary": "AliExpress · Traduccion IA · Control Bluetooth · Lentes fotocromaticos",
    "description": "Opcion accesible de gafas inteligentes con traduccion y funciones de conectividad.",
    "price": 100,
    "originUrl": "https://es.aliexpress.com/item/1005011803378382.html",
    "sourcePrice": 26.35,
    "priceRule": "+70 y redondeo a decena superior",
    "lumenAnsi": null,
    "rawTitle": "Gafas Inteligentes con Traduccion IA, Lentes con Cambio de Color y Control Bluetooth, Llamadas Bluetooth, Gafas Inteligentes con IA",
    "image": "assets/products/ali-gls-003-gafas-ia-con-traduccion-bluetooth-y-control-tactil.jpg"
  }
];
